# Generated by Django 5.2.7 on 2025-10-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_band_like_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='album',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
