# Generated by Django 5.2.7 on 2025-10-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='album',
        ),
    ]
